### ISSUE TITLE
Full Integer Quantization support?

### ISSUE THREAD

**Issue by hoangtv2000** [levipereira/yolov9-qat#15]
Hi @levipereira,
I have a question that does your method support Full Integer Quantization?
Thank you.

**Comment by levipereira** [comment]
Yes, it is entirely possible. To achieve this, you need to add Quantize/Dequantize (Q/DQ) nodes at every point where TensorRT generates *Reformat operations. There is no need to convert the entire model to INT8; you only need to quantize the Convolution layers since this is where the most significant performance gains are realized. This is because Q/DQ nodes can be commuted with other operations like activation, pooling, slicing, etc. Quantizing activations, for example, can result in a high cost to model accuracy with minimal performance (latency) gains. TensorRT handles this efficiently by ensuring that INT8 calculations are performed primarily in CONV layers, where the majority of computations occur.

* Reformat operations occur in TensorRT when there are mismatched tensor precisions or layouts between nodes.  
eg. Add Node Output: When one output is in FP16 and the other in INT8, a Reformat operation is required.

https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#tensorrt-process-qdq
